##### KATOGORİK VERİLERİN SINIFLANDIRILMASI VE KARMAŞIKLIK MATRISI
CLASSIFICATION AND CONFUSION MATRIX 

In [89]:
# 1. KUTUPHANELERİN YUKLENMESİ [2.1-2.2]

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [90]:
# 2. VERİNİN (.CSV) İÇE YÜKLEMESİ ve PD DATAFRAME OLUŞTURMA (comma seperated value virgulle ayrılan veriler ) [2.3]-[2.4]

veriler = pd.read_csv("20220316_KatVeriler_Sınıflandırma_Karmaşıklık Matrisi_veriler.csv")
print(veriler)
# Çalışma dizini .py ile read edilen dosya aynı yerde olmalıdır.Aksi halde absolute tam adres verilmelidir.

# Dataframe içindeki sutunları ayırma _ 1: Değişkenlerin Dataframe içindeki list of list durumu
# BİLGİ AMAÇLI KULLANILMAYACAK.
boy = veriler[["boy"]]      
kilo = veriler[["kilo"]] 
yas = veriler[["yas"]] 
boykiloyas = veriler[["boy","kilo","yas"]]
ulke = veriler[["ulke"]] 
# ulke verilerinin sayısal olmadığı ve KATAGORİK olduğu tespit edildi.
# (2d1 maddesi) ON İŞLEME GEREKİYOR.[OneHotENcoding yapılacak]
cinsiyet = veriler[["cinsiyet"]] 
# cinsiyet verilerinin sayısal olmadığı ve KATAGORİK olduğu tespit edildi.
#(2d2 maddesi) ON İŞLEME GEREKİYOR. [leENcoding yapılacak]

# DEĞİŞKENLERİ GÖRELİM :
print(ulke), print(boy),print(kilo), print(yas), print(boykiloyas), print(cinsiyet)

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k
   ulke
0    tr
1    tr
2    tr
3    tr
4    tr
5    tr
6    tr
7    tr
8    tr
9    us
10   us
11   us
12   us
13   us
14   us
15   fr
16   fr
17   fr
18   fr
19   fr
20   fr
21   fr
    boy
0   130
1   125
2   135
3   133
4   129
5   180
6

(None, None, None, None, None, None)

In [91]:
# 2d1. ON İŞLEME Katogorik Verilerle Çalışma [2.6] : Katogorik veri yoktur.
# 2d2. ON İŞLEME Eksik Verilerle Çalışma [2.5] : Eksik Veri yoktur.
# ARRAY - DATAFRAME DONUŞUMLERİNE GEREK YOKTUR.

In [92]:
# 3. BAĞIMSIZ (X) VE BAĞIMLI (Y) DEĞİŞKENLERİN BELİRLENMESİ İLE TEST VE TRAIN OLARAK BÖLÜNMESİ [2.8]

# --------------------------------------------------------------------------------------------------------
# 3a. BAĞIMSIZ VE BAĞIMLI DEĞİŞKENLERİN BELİRLENMESİ 

# Bu dataframe içinde ulke kolonloru buu ornekte alınmıyor. İstenirse OHE yapılıp alınabilir.
# x bağımsız değişkenleri boy, kilo, yas, cinsiyet oluyor iloc ile alıcaz bu değerleri numpy array yapıcaz
# y bağımlı değişkenide cinsiyet ularak tahmin edilecek lojistik regresyonla

x = veriler.iloc[:,1:4].values # bağımsız değişkenler, ülke değişkeni OHE yapılması gerektiği için alınmadı
y = veriler.iloc[:,-1:].values # bağımlı tahmin edilecek Cinsiyet değişkeni

#---------------------------------------------------------------------------------------------------------
# 3b. DEĞİŞKENLERİN TEST VE TRAIN EDİLMESİ

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33,random_state=0)

# 4. VERİLERİN ÖZNİTELİK ÖLÇEKLENMESİ [2.9] [3.4]

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test) 
# UNUTMA Trainde fit edilen sc objesi testtede kullanılır. Bu yuzden test işleminde sadece transform yapılacak. 

print(X_train), print(X_test)

# index numaralarına dikkat: rastgele alınmış satırlar

[[ 0.45049444 -0.29657884 -0.26680787]
 [ 1.00824945  0.5096549   0.        ]
 [ 1.13696215  0.91277178 -0.17787191]
 [-1.6089087  -1.18343596 -1.15616745]
 [-1.35148331 -1.34468271 -1.33403936]
 [ 0.57920713  0.91277178  0.44467979]
 [ 0.87953676  0.5096549   0.17787191]
 [ 0.79372829  1.51744708  0.71148766]
 [ 0.36468597  0.91277178  0.88935957]
 [ 0.70791983  0.8321484   0.26680787]
 [-1.43729177 -1.50592946 -1.42297532]
 [-1.56600447 -1.50592946 -1.33403936]
 [ 0.32178174  0.10653803  1.95659106]
 [-0.27887751 -0.37720222  1.2451034 ]]
[[-0.10726058 -0.05470872  0.6225517 ]
 [-0.06435635 -0.49813728  0.17787191]
 [ 0.02145212 -0.21595547  2.66807872]
 [-0.19306904 -0.33689053  1.42297532]
 [-1.78052563 -1.26405934 -1.2451034 ]
 [-0.02145212 -0.45782559  1.51191128]
 [-0.49339867 -0.69969571  1.68978319]
 [-0.32178174 -1.10281259  0.35574383]]


(None, None)

In [93]:
# 5. LOJISTIK REGRESYON VE VİZUALİZATION [GÖRSELLEŞTİRME] :
#------------------------------------------------------------------------------------------------------------------
# Önemli Bilgiler :
# 1. Burada Log&Reg Regresyonla karıştırılmamalıdır. Sınıflandırma için kullanılır.SupportVektorM ile en cok kullanılan sınıflandırma algoritmasıdır.

from sklearn.linear_model import LogisticRegression
# sklearn kutuphanesinden Lojsitk Regresyon işlemler yapabiliyoruz.

logr = LogisticRegression(random_state=0)
logr.fit(X_train,y_train) # logr objesi train değişkenleri ile fit/eğitildi edildi.


y_pred = logr.predict(X_test)
print(y_pred)
print(y_test)

# TAM TERSİNİ TAHMİN ETTİ


['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\utils\validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


KARMAŞIKLIK MATRISI CONFUSION MATRIX

In [96]:
# 10. CONFUSION MATRIX (KARMAŞIKLIK MATRISI) :

#  G                TAHMİN PREDICTION
#  E -----------------------------------------------
#  R   True-Positive  (TP)   +   False-Negative (FN)
#  Ç   +++++++++++++++++++++++++++++++++++++++++++++
#  E   False-Positive (FP)   +   True-Negative  (TN)
#  K

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred) # y_test gerçek ve y_pred tahmini cinsiyet karşılaştrması

# Matris değerlerinin incelenmesi:
Satır0 = cm[0] # TP+FN
TP = Satır0[0]
FN = Satır0[1]
Satır1 = cm[1] # FP+TN
FP = Satır1[0]
TN = Satır1[1]


print(cm)
print (y_test,y_pred) # Hiçbiri tutmamış ..😎😯

print("Accuracy Rate    [Doğruluk Oranı]= ","%", ((TP+TN)/(TP+FN+FP+TN))*100)
print("Error Rate       [Hata Oranı]=     ","%", ((100-((TP+TN)/(TP+FN+FP+TN))*100)))
print("Precision Rate   [Kesinlik Oranı]= ","%", ((TP)/(TP+FP))*100)
print("Specificity-True/Neg rate (TNR)=   ","%", ((TN/(FP+TN))*100))
print("Sensitivity-Recall Rate -True/Pos Rate [Hassasiyet Oranı]=","%",((TP)/(TP+FN))*100)
# Burada en önemli nokta tahmin edilen bağımlı değişkeninin balanced olması gerkiyor. Yani %90 Erkek ve
# 10% kadın olan veri setinde Accuracy Rate in 90% olması başarı değildir. Kadını bulamama ihtimallerine
# rağmen 90% erkek bulacağı için Accuracy Rate hata yaptırır. Bundan dolayı diğer değerlerede bakılmalıdır.

[[0 1]
 [7 0]]
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']] ['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
Accuracy Rate    [Doğruluk Oranı]=  % 0.0
Error Rate       [Hata Oranı]=      % 100.0
Precision Rate   [Kesinlik Oranı]=  % 0.0
Specificity-True/Neg rate (TNR)=    % 0.0
Sensitivity-Recall Rate -True/Pos Rate [Hassasiyet Oranı]= % 0.0
