In [1]:
# 1. KUTUPHANELERİN YUKLENMESİ [2.1-2.2]

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
## 2. VERİNİN (.CSV) İÇE YÜKLEMESİ ve PD DATAFRAME OLUŞTURMA (comma seperated value virgulle ayrılan veriler ) [2.3]-[2.4]

veriler = pd.read_csv("20220225_PCA Boyut İndirgeme Analizi_PSA_Wine.csv")
# MUSTERİ KAYIP ANALİZİ [KAYBEDECEĞİMİZİ NASIL ANLARIZ]
# YENİ MUSTERİ KAZANMAK ELDEKİ MUSTERİYİ KAYETMEMEKTEN 3 KAT DAHA PAHALI BUNDAN DOLAYI BU ANALİZ ÖNEMLİ
print(veriler)
veriler.info()
'''
178 rows x 14 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Alcohol               178 non-null    float64 : Bağımsız Değişken
 1   Malic_Acid            178 non-null    float64 : Bağımsız Değişken
 2   Ash                   178 non-null    float64 : Bağımsız Değişken
 3   Ash_Alcanity          178 non-null    float64 : Bağımsız Değişken
 4   Magnesium             178 non-null    int64   : Bağımsız Değişken
 5   Total_Phenols         178 non-null    float64 : Bağımsız Değişken
 6   Flavanoids            178 non-null    float64 : Bağımsız Değişken
 7   Nonflavanoid_Phenols  178 non-null    float64 : Bağımsız Değişken
 8   Proanthocyanins       178 non-null    float64 : Bağımsız Değişken
 9   Color_Intensity       178 non-null    float64 : Bağımsız Değişken
 10  Hue                   178 non-null    float64 : Bağımsız Değişken
 11  OD280                 178 non-null    float64 : Bağımsız Değişken
 12  Proline               178 non-null    int64   : Bağımsız Değişken
 13  Customer_Segment      178 non-null    int64   : BAĞIMLI DEĞİŞKEN Y

dtypes: float64(11), int64(3)
memory usage: 19.6 KB

'''
# 2a. ON İŞLEME 
  # 2a1. Pandas Dataframe içindeki sutunları X (BAGIMSIZ) VE Y(BAĞIMLI) DEĞİŞKEN DİZİLERİ OLARAK AYIRMA
     # İlk 3 değişken gereksiz bu yüzden bağımsız x değişkenlerinden ayrılacak.
      # Excited 0 Bırakmayanlar Y Bağımlı Değişkeni 
  
X = veriler.iloc[:,0:13].values 
# [ tüm satırlar, 0-13 arasındaki tüm sütünlar] iloc ile X Bağımsız değişkenleri alındı.
# Pandas Dataframeden .values ile numpy array yapıldı
Y = veriler.iloc[:,13].values 
# [ tüm satırlar, 13 ncü sutun ] Y Bağımlı değişkeni customer segment alındı.
# Pandas Dataframeden .values ile numpy array yapıldı

print (X),
print (Y)

     Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0      14.23        1.71  2.43          15.6        127           2.80   
1      13.20        1.78  2.14          11.2        100           2.65   
2      13.16        2.36  2.67          18.6        101           2.80   
3      14.37        1.95  2.50          16.8        113           3.85   
4      13.24        2.59  2.87          21.0        118           2.80   
..       ...         ...   ...           ...        ...            ...   
173    13.71        5.65  2.45          20.5         95           1.68   
174    13.40        3.91  2.48          23.0        102           1.80   
175    13.27        4.28  2.26          20.0        120           1.59   
176    13.17        2.59  2.37          20.0        120           1.65   
177    14.13        4.10  2.74          24.5         96           2.05   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0          3.06               

In [3]:
# 3. VERİLERİN TEST VE TRAIN OLARAK BÖLÜNMESİ [2.8]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)
# Dataset 20% test ve 80%train olarak ikiye ile 13 X bağımsız ve 1 Y bağımlı değişken olarak 4 e ayrıldı.

print(x_train) # train 13 bağımsız değişkenler % 80 Dataset
print(y_train) # train 1 bağımlı değişken      % 80 Dataset
print(x_test)  # test 13 bağımsız değişken     % 20 Dataset
print(y_test)  # train 1 bağımlı değişken      % 20 Dataset

[[1.369e+01 3.260e+00 2.540e+00 ... 9.600e-01 1.820e+00 6.800e+02]
 [1.269e+01 1.530e+00 2.260e+00 ... 9.600e-01 2.060e+00 4.950e+02]
 [1.162e+01 1.990e+00 2.280e+00 ... 1.160e+00 2.960e+00 3.450e+02]
 ...
 [1.242e+01 1.610e+00 2.190e+00 ... 1.060e+00 2.960e+00 3.450e+02]
 [1.390e+01 1.680e+00 2.120e+00 ... 9.100e-01 3.330e+00 9.850e+02]
 [1.416e+01 2.510e+00 2.480e+00 ... 6.200e-01 1.710e+00 6.600e+02]]
[3 2 2 3 1 1 2 2 2 1 3 2 3 1 3 3 1 3 1 2 3 3 2 3 3 1 2 3 2 2 3 2 1 2 2 2 1
 1 2 2 3 3 2 2 2 3 3 1 3 2 2 2 2 2 1 1 2 1 3 1 3 1 1 2 1 2 2 1 3 2 1 2 2 2
 3 1 3 3 1 1 2 3 1 1 2 2 1 1 1 3 2 1 2 3 1 2 3 3 1 1 3 1 3 2 1 1 2 1 3 2 3
 1 3 3 3 1 2 2 2 2 3 3 2 2 1 2 3 3 1 1 3 2 2 2 1 1 1 2 2 2 1 3]
[[1.374e+01 1.670e+00 2.250e+00 1.640e+01 1.180e+02 2.600e+00 2.900e+00
  2.100e-01 1.620e+00 5.850e+00 9.200e-01 3.200e+00 1.060e+03]
 [1.279e+01 2.670e+00 2.480e+00 2.200e+01 1.120e+02 1.480e+00 1.360e+00
  2.400e-01 1.260e+00 1.080e+01 4.800e-01 1.470e+00 4.800e+02]
 [1.237e+01 1.130e+00 2.160e+00 1

In [4]:
# 4. VERİLERİN ÖZNİTELİK SCALER ÖLÇEKLENMESİ [2.9] ANN-DEEP LEARNING İÇİN DEĞERLER 0-1 ARASI OLACAK

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train = sc.fit_transform(x_train) # X_train scale edilmiş bağımsız değişkenler train datalar 
X_test = sc.fit_transform(x_test)



In [5]:
# 21. PCA VE LDA İLE BOYUT AZALTMA İŞLEMLERİ:
          
# 21a.PCA MODEL OLUŞTURMA VE BOYUT DÖNÜŞTÜRME: 

from sklearn.decomposition import PCA
pca = PCA(n_components = 2) # 2 boyutlu PCA obje urettik.

# 21b.LDA MODEL OLUŞTURMA VE BOYUT DÖNÜŞTÜRME: 

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 2) # 2 boyutlu LDA obje urettik.

# --------------------------------------------------------------------------------------

# 13 adet X Bağımsız X_train eğitim ve X_test test değişkenlerine PCA uygulanması
# Burada önemli olan pca objesinin fit edilmesi. Sadece train set ile eğtiliyor. Eğitilen pca ile train ve test setler transform ediliyor.

X_train_pca = pca.fit_transform(X_train) # Fit the model with X_train and apply the dimensionality reduction on X_train_pca.
# Ölçeklendirilmiş X_train eğitim verisi (toplam verinin 80%) ile fit eğitilip veri yeni hal alıcak.
# Bu süreçte 13 bağımsız değişken 2 boyuta dönüşecek. Kayıpalr olabilir.

X_train_lda = lda.fit_transform(X_train,y_train) 
# DİKKAT : neden scale edilmemiş y_trainde fit_transform ediliyor?.
# LDA SUPERVİSED gözetimli yani etiketleri [y_train] bağımlı değişkenleride kullanacaktır. LDA-PCA arasındaki TEK FARK BU.... 
# Etiketler sayesinde sınıflar araındaki farkları maksimize ediyor.

X_test_pca = pca.transform(X_test) # Apply dimensionality reduction to X.
# Ölçeklendirilmiş X_test verisi; X_Train ile eğitilen (fit edilen) pca objesi ile transform edilerek 13 (X) değişkenden 2 (X) Değişkene boyut azalttı.
# BURADA DİKKAT TEST İÇİN FIT YOK .. daha önce it edilen X_train pca objesi ile eğitilior. 
# TRAINDE FİT EDİLİP EĞİTİLEN MODEL TESTTE TRANSFORM EDİLİYOR. 
# TEKRAR TEST KUMESİ İLE TRAIN YAPILMIYIR.

X_test_lda = lda.transform(X_test) # lda objesi trainde fit edildiği için sadece X_test verilerini yazıyoruz.
# Yani ölçekli X_train ve ölçeksik y_train ile fit edilen lda objesi ile _test verileri transform ediliyor.


In [6]:
# 21a. SCALE - FIT VE TRANSFORM EDİLEN VERİLERİN SINIFLANDIRILMASI (LOJİSTİK REGRESYONLA YAPALIM) İŞLEMLERİ: 
     # 5. LOJISTIK REGRESYON VE VİZUALİZATION [GÖRSELLEŞTİRME] :

from sklearn.linear_model import LogisticRegression # LR ile sınıflandırma yapacağız.
      
    # PCA boyut azaltma yapılmadan yapılan Sınıflandırma işlemi:
logr = LogisticRegression(random_state=0) # random state 0 ile aşağıdaki ve bu sınıflandırada aynı algoritma kullanılacak.
logr.fit(X_train,y_train) 
# Dikkat Boyut azaltma olmayan X_train ile fit edip eğitim setindeki y değişkeni sınıflandırılıyor
# Sınıflandırma yapılan set logr.fit objesinde,

    # PCA boyut azaltma yapıldıktan sonra yapılan Sınıflandırma işlemi:
logr_pca = LogisticRegression(random_state=0)
logr_pca.fit(X_train_pca,y_train) # Dikkat Boyut azaltma yapılan X_train_pca ile fit edip eğitim setindeki y değişkeni sınıflandırılıyor

   # LDA boyut azaltma yapıldıktan sonra yapılan Sınıflandırma işlemi:
logr_lda = LogisticRegression(random_state=0)
logr_lda.fit(X_train_lda,y_train) # Ölçeklenmiş ve 2 Boyuta LDA ile inmiş X_train eğitim verilerinden y_train verilerini öğrenecek

LogisticRegression(random_state=0)

In [7]:
# 11.e PREDICT TAHMİN ETMEK :
'''
Model.predict(
    x,
    batch_size=None,
    verbose=0,
    steps=None,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False,
)
'''
y_pred = logr.predict(X_test) 
# PSA YAPILMADAN 13 BAĞIMSIZ DEĞİŞKEN (X_test) İLE YAPILAN BAĞIMLI DEĞİŞKEN TAHMİNİ 
y_pred_psa = logr_pca.predict(X_test_pca) 
# PSA YAPILDIKTAN SONRA 2 BAĞIMSIZ DEĞİŞKEN (X_test_psa) İLE YAPILAN BAĞIMLI DEĞİKEN TAHMİNİ 
y_pred_lda = logr_lda.predict(X_test_lda) 
# LDA YAPILDIKTAN SONRA 2 BAĞIMSIZ DEĞİŞKEN (X_test_lda) İLE YAPILAN BAĞIMLI DEĞİKEN TAHMİNİ 

In [8]:
# 12. KARŞILAŞTIRMA MATRIXI

from sklearn.metrics import confusion_matrix

print(" Y_test (GERÇEK SONUÇ) İLE Y_Pred (PSA olmadan tahmin Karşılaştırması) :")
cm_1 = confusion_matrix(y_test,y_pred)
print(cm_1)


print(" Y_test (GERÇEK SONUÇ) İLE Y_Pred_psa (PSA yapılarak tahmin Karşılaştırması) :")
cm_2 = confusion_matrix(y_test,y_pred_psa)
print(cm_2)

print(" Y_Pred (Tahmni Sonuç) İLE Y_Pred_psa (PSA yapılarak tahmin Karşılaştırması) :")
cm_3 = confusion_matrix(y_pred,y_pred_psa)
print(cm_3)

print(" Y_test (GERÇEK SONUÇ) İLE Y_Pred_lda (LDA yapılarak tahmin Karşılaştırması) :")
cm_4 = confusion_matrix(y_test,y_pred_lda)
print(cm_4) # LDA - Gerçek sonuç mukemmel çıktı % 100 başarılı oldu.


 Y_test (GERÇEK SONUÇ) İLE Y_Pred (PSA olmadan tahmin Karşılaştırması) :
[[14  0  0]
 [ 0 15  1]
 [ 0  0  6]]
 Y_test (GERÇEK SONUÇ) İLE Y_Pred_psa (PSA yapılarak tahmin Karşılaştırması) :
[[14  0  0]
 [ 1 15  0]
 [ 0  0  6]]
 Y_Pred (Tahmni Sonuç) İLE Y_Pred_psa (PSA yapılarak tahmin Karşılaştırması) :
[[14  0  0]
 [ 1 14  0]
 [ 0  1  6]]
 Y_test (GERÇEK SONUÇ) İLE Y_Pred_lda (LDA yapılarak tahmin Karşılaştırması) :
[[14  0  0]
 [ 0 16  0]
 [ 0  0  6]]
