In [18]:
# MÜSTERİ KAYBININ ÖNLENMESİNE DAİR VERİ BİLİMİ DL PROJESİ

In [19]:
# 1. KUTUPHANELERİN YUKLENMESİ [2.1-2.2]

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [20]:
## 2. VERİNİN (.CSV) İÇE YÜKLEMESİ ve PD DATAFRAME OLUŞTURMA (comma seperated value virgulle ayrılan veriler ) [2.3]-[2.4]

veriler = pd.read_csv("model.csv")
# MUSTERİ KAYIP ANALİZİ [KAYBEDECEĞİMİZİ NASIL ANLARIZ]
# YENİ MUSTERİ KAZANMAK ELDEKİ MUSTERİYİ KAYETMEMEKTEN 3 KAT DAHA PAHALI BUNDAN DOLAYI BU ANALİZ ÖNEMLİ
print(veriler)
veriler.info()
'''
[10000 rows x 14 columns]
<class 'pandas.core.frame.DataFrame'>
PANDAS DATAFRAME OLDUĞU YAZILI YUKARIDA SATIR İNDEX NU VAR.

RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64    ÖĞRENME İÇİN GEREKSİZ BAĞIMSIZ DEĞİŞKEN OVERFITTING YAPAR
 1   CustomerId       10000 non-null  int64    ÖĞRENME İÇİN GEREKSİZ BAĞIMSIZ DEĞİŞKEN OVERFITTING YAPAR
 2   Surname          10000 non-null  object   ÖĞRENME İÇİN GEREKSİZ BAĞIMSIZ DEĞİŞKEN OVERFITTING YAPAR
YUKARDAKİ DEĞİŞKENLER BAĞIMSIZ DEĞİŞKEN SIFATI TAŞIMIYOR.****************************************************** 

 3   CreditScore      10000 non-null  int64    DL(0-1) ARASINDA DEĞİL OHE YAPILMALI VE SAYISAL VERİ OLMALI
 4   Geography        10000 non-null  object   KATOGORİK VERİLERİN DL İÇİN[0-1] ARASINA ENCODING YAPILMASI LAZIM
 5   Gender           10000 non-null  object   KATOGORİK VERİLERİN DL İÇİN[0-1] ARASINA ENCODING YAPILMASI LAZIM
 7   Tenure           10000 non-null  int64    DL(0-1) ARASINDA DEĞİL OHE YAPILMALI VE SAYISAL VERİ OLMALI
 8   Balance          10000 non-null  float64  DL(0-1) ARASINDA DEĞİL OHE YAPILMALI VE SAYISAL VERİ OLMALI
 9   NumOfProducts    10000 non-null  int64    DL(0-1) ARASINDA DEĞİL OHE YAPILMALI VE SAYISAL VERİ OLMALI
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 YUKARIDAKİ DEĞİŞKENLER BAĞIMSIZ X DEĞİŞKEN SIFATI TAŞIYOR.*****************************************************
 
 13  Exited           10000 non-null  int64    BAĞIMLI (Y) DEĞİŞKENİ MÜŞTERİ BİZİ BIRAKTI MI BIRAKMADI MI? BUNU TAHMİN EDECEK 
 YUKARIDAKİ DEĞİŞKEN BAĞIMLI Y DEĞİŞKENİ YANİ SONUÇTA DEĞERLENDİRİLİECEK DEĞİŞKEN 0: BİZİ BIRAKMIYCAK ***************
 
 MODEL YAPICAZ.. 
 **************************************************************************************************************
dtypes: float64(2), int64(9), object(3)        (0) BIRAKMAYANLAR + (1) BIRAKANLAR
'''
# 2a. ON İŞLEME 
  # 2a1. Pandas Dataframe içindeki sutunları X (BAGIMSIZ) VE Y(BAĞIMLI) DEĞİŞKEN DİZİLERİ OLARAK AYIRMA
     # İlk 3 değişken gereksiz bu yüzden bağımsız x değişkenlerinden ayrılacak.
      # Excited 0 Bırakmayanlar Y Bağımlı Değişkeni 
  

X = veriler.iloc[:,3:13].values # X Bağımsız değişkenleri (tum satırlar,İNDEX 3 dahil:İndex 13 hariç tum sutunlar) alındı.Pandas Dataframeden .values ile numpy array yapıldı
Y = veriler.iloc[:,13].values # Y Bağımlı değişkeni alındı.Pandas Dataframeden .values ile numpy array yapıldı

X,Y,type(Y)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0], dtype=int64),
 numpy.ndarray)

In [21]:
# 2d. ON İŞLEME - ENCODING (LE-OHE-CT) Katogorik Verilerle Çalışma [2.6] GEOGRAPHY AND GENDER katogorik verileri
 # [CT:Column Transformer öğereneceğiz burada]
from sklearn import preprocessing

# 2d1. KATOGORİK VERİ ENCODING -- [LABEL ENCODING] ---------------------------------------------------------------------
       # geo katogorik verilerin LE ile encode edilmesi
le = preprocessing.LabelEncoder()
X[:,1] = le.fit_transform(X[:,1])
       # İlk 3 sutunu temizlenen ve O DEĞİL 1 nci INDEX KOLUNU Kat Geo VERİLERİ FİT edilip LAbel Encodingle SAYISAL VERİYE çevrildi. 
    
       # gender katogorik verilerin LE ile encode edilmesi (le2 yaptık cunku yukarıdki le geo ile train edildi.)
le2 = preprocessing.LabelEncoder()
X[:,2] = le2.fit_transform(X[:,2])
       # İlk 3 sutunu temizlenen ve 2 nci INDEX KOLONU Gender VERİLERİ FİT edilip LE ile sayısala cevrildi.

# 2d2. KATOGORİK VERİ ENCODING -- COLUMN TRANSFORMER VE ONE HOT ENCODER İLE FARKLI KATOGORİKLERİN DÖNÜŞTÜRÜLMESİ--------

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])], remainder='passthrough')
X = ohe.fit_transform(X)
X = X[:,1:]
X


array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [22]:
# 3. VERİLERİN TEST VE TRAIN OLARAK BÖLÜNMESİ [2.8]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.33,random_state=0)

print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0.0 0.0 477 ... 0 0 163112.9]
 [0.0 0.0 794 ... 1 1 74275.08]
 [0.0 0.0 570 ... 0 1 62810.91]
 ...
 [0.0 0.0 738 ... 1 0 181429.87]
 [0.0 1.0 590 ... 1 1 148750.16]
 [1.0 0.0 623 ... 1 0 118855.26]]
[1 0 0 ... 0 0 1]
[[1.0 0.0 597 ... 1 1 192852.67]
 [0.0 0.0 523 ... 1 0 128702.1]
 [0.0 1.0 706 ... 1 1 75732.25]
 ...
 [0.0 1.0 684 ... 0 0 120284.67]
 [1.0 0.0 577 ... 0 0 125140.72]
 [0.0 0.0 736 ... 0 1 192131.77]]
[0 1 0 ... 0 1 0]


In [23]:
# 4. VERİLERİN ÖZNİTELİK ÖLÇEKLENMESİ [2.9] ANN-DEEP LEARNING İÇİN DEĞERLER 0-1 ARASI OLACAK

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)
X_train

array([[-0.56953701, -0.57436296, -1.78451879, ..., -1.56299709,
        -1.03339307,  1.0890591 ],
       [-0.56953701, -0.57436296,  1.47401668, ...,  0.63979645,
         0.967686  , -0.4551902 ],
       [-0.56953701, -0.57436296, -0.82854466, ..., -1.56299709,
         0.967686  , -0.65446947],
       ...,
       [-0.56953701, -0.57436296,  0.89837634, ...,  0.63979645,
        -1.03339307,  1.40745917],
       [-0.56953701,  1.74105933, -0.62295883, ...,  0.63979645,
         0.967686  ,  0.83939459],
       [ 1.75581215, -0.57436296, -0.2837422 , ...,  0.63979645,
        -1.03339307,  0.31973777]])

In [24]:
 # 11a.MODEL OLUŞTURMA: Sequential Model keras tf üzerinden kuruldu ve model objesi yaratıldı.

from tensorflow import keras
from tensorflow.keras.models import Sequential
model = Sequential() 

# Bir yapay sinir ağı model obje olarak temel Seq modelden boş oluşturuldu altta içini dolduracağız.


In [25]:
 # 11b. KATMAN /LAYER(DENSE) OLUŞTURMA: Layers/Katmanlar .add() ile oluşturuldu:Her Noron Katmanı Dense ile oluşturuldu

'''
tf.keras.layers.Dense(
    units, [ kaç tane katmanda noron olacak ]
    activation=None, [ Akt Fonk ne olacak]
    use_bias=True, [ Düzeltme Yapılacak mı]
    kernel_initializer="glorot_uniform",
    bias_initializer="zeros",
    kernel_regularizer=None,
    bias_regularizer=None,
    activity_regularizer=None,
    kernel_constraint=None,
    bias_constraint=None,
    **kwargs
)
'''
# On işleme neticesinde 11 adet Bagımsız Değişken (x) oluşturduk. Çıkış sadece 1 adet (y) excited kolunu oluşturduk.
# İpucu [ÜCGEN YAPI]: Bundan dolayı giriş için 11 units,çıkış için 1 units topla ve böl ikiye 6 ile oluşturmak işe yarıyor.

from tensorflow.keras.layers import Dense
model.add(Dense(units=6,kernel_initializer="glorot_uniform", activation='relu',input_dim=11))
# 1 NCİ GİZLİ KATMAN [GİRİŞ KATMANI - Input_dimension X Bağımsız dğişken sayısı BELİRTİLEN]
model.add(Dense(units=6,kernel_initializer="glorot_uniform", activation='relu'))  
# 2 NCİ GİZLİ KATMAN 
model.add(Dense(units=1,kernel_initializer="glorot_uniform",activation='sigmoid'))          
# ÇIKIŞ KATMANI 1 Noron var (o: Bırakır, 1: Bırakmaz verecek)+ cıkışlar genelde sigmoid fonk olur.  


In [26]:
# 11c. COMPILE / DERLEME ETMEK :

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy']
             )

'''
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=[tf.keras.metrics.BinaryAccuracy(),
                       tf.keras.metrics.FalseNegatives()])

'''

'\nmodel.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n              loss=tf.keras.losses.BinaryCrossentropy(),\n              metrics=[tf.keras.metrics.BinaryAccuracy(),\n                       tf.keras.metrics.FalseNegatives()])\n\n'

In [27]:
# 11.d. TRAIN VE FIT ETMEK :

model.fit( X_train , y_train , epochs=50) 

# scale edilmiş X bağımsız değişkenlerinden zaten(0-1 arası olan) bağımlı y değişkeni öğrenecek,
# 50 tur da öğrenecek


'''
Model.fit( x=None,y=None,
            batch_size=None,
            epochs=1,
            verbose="auto",
            callbacks=None,
            validation_split=0.0,
            validation_data=None,
            shuffle=True,
            class_weight=None,
            sample_weight=None,
            initial_epoch=0,
            steps_per_epoch=None,
            validation_steps=None,
            validation_batch_size=None,
            validation_freq=1,
            max_queue_size=10,
            workers=1,
            use_multiprocessing=False,)
'''

Epoch 1/50
210/210 [==============================] - 0s 1ms/step - loss: 0.5392 - accuracy: 0.7919
Epoch 2/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4615 - accuracy: 0.7987
Epoch 3/50
210/210 [==============================] - 0s 997us/step - loss: 0.4409 - accuracy: 0.8033
Epoch 4/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4301 - accuracy: 0.8103
Epoch 5/50
210/210 [==============================] - 0s 926us/step - loss: 0.4232 - accuracy: 0.8139
Epoch 6/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4177 - accuracy: 0.8197
Epoch 7/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4130 - accuracy: 0.8240
Epoch 8/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4087 - accuracy: 0.8264
Epoch 9/50
210/210 [==============================] - 0s 983us/step - loss: 0.4047 - accuracy: 0.8287
Epoch 10/50
210/210 [==============================] - 0s 1ms/step - loss: 0.4010 - accuracy: 

'\nModel.fit( x=None,y=None,\n            batch_size=None,\n            epochs=1,\n            verbose="auto",\n            callbacks=None,\n            validation_split=0.0,\n            validation_data=None,\n            shuffle=True,\n            class_weight=None,\n            sample_weight=None,\n            initial_epoch=0,\n            steps_per_epoch=None,\n            validation_steps=None,\n            validation_batch_size=None,\n            validation_freq=1,\n            max_queue_size=10,\n            workers=1,\n            use_multiprocessing=False,)\n'

In [31]:
# 11.e PREDICT TAHMİN ETMEK :
'''
Model.predict(
    x,
    batch_size=None,
    verbose=0,
    steps=None,
    callbacks=None,
    max_queue_size=10,
    workers=1,
    use_multiprocessing=False,
)
'''
y_pred = model.predict(X_test) 
# 33% scale yani normailze edilen (X/0-1 arasına alınan) X bağımsız test verileri ile scale edilmemiş y verilerini tahmin edecek.
# BAKALIM GERÇEK VERİLERLE NE KADAR YAKIN OLACAK.
y_pred = (y_pred > 0.5)
# sacle edildiği için 0.5 altını 0 ve üstünü 1 kabul edecek,boolean döndürcek False/True
# yeni y_pred =1 (Müşteri bırakır olarak belirledik)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [33]:
# 12. KARŞILAŞTIRMA MATRIXI

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
# Memnuniyet y test gercek değerleri ile tahmin değerlerini Matrixde [Accuracy] karşilastıracağız.
cm

array([[2490,  127],
       [ 368,  315]], dtype=int64)